### ISSUE TITLE
Appears to be out of date with jenkinsci/sumologic-jenkins-plugin

### ISSUE THREAD

**Issue by rpocase** [SumoLogic/sumologic-jenkins-plugin#16]
The release repository [jenkinsci/sumologic-jenkins-plugin](https://github.com/jenkinsci/sumologic-jenkins-plugin), seems very out of date with this repository. This should be brought up to date.

**Comment by SumoSourabh** [comment]
Done. Is put in sync with jenkinsci/sumologic-jenkins-plugin.
