### ISSUE TITLE
Http_source_URL in global config is in clear text - not hidden

### ISSUE THREAD

**Issue by Constantin07** [SumoLogic/sumologic-jenkins-plugin#25]
Looks like source URL is displayed in clear text in Global Configuration.

Should it be treated as sensitive information like passwords ?

It would be nice (more secure) to hide (with stars) the value so it cannot be leaked when looking at global configuration.

**Comment by SumoSourabh** [comment]
https://github.com/SumoLogic/sumologic-jenkins-plugin/pull/26 - PR raised.
