### ISSUE TITLE
"Search log" Link doesn't work

### ISSUE THREAD

**Issue by anfurny** [SumoLogic/sumologic-jenkins-plugin#29]
Takes me to a login page. Even if I have sumo open in other tabs, or just signed in on the same tab.

After logging in, I still don't go to the right place.

<img width="706" alt="Is_CI_working__132__Jenkins_" src="https://user-images.githubusercontent.com/1141879/81210803-6cbbae80-8fa0-11ea-8ab0-0f08e66d8221.png">

<img width="1440" alt="Sumo_Logic" src="https://user-images.githubusercontent.com/1141879/81210922-9674d580-8fa0-11ea-9d2d-de96711bfd06.png">

**Comment by SumoSourabh** [comment]
Closing it as no input.
