### ISSUE TITLE
Job output isn't uploaded to sumo

### ISSUE THREAD

**Issue by anfurny** [SumoLogic/sumologic-jenkins-plugin#30]
My job has the post-build action 
![image](https://user-images.githubusercontent.com/1141879/81211166-fb303000-8fa0-11ea-80aa-8fd2f878dc23.png)

My job has some console output 
![image](https://user-images.githubusercontent.com/1141879/81211251-169b3b00-8fa1-11ea-97a5-8b9111746241.png)

That console output shows up nowhere in sumo:
![image](https://user-images.githubusercontent.com/1141879/81211346-36cafa00-8fa1-11ea-9dcd-8f6d1e25ffab.png)

Using this version:
![image](https://user-images.githubusercontent.com/1141879/81211428-5e21c700-8fa1-11ea-9c54-ffd4bc2c007e.png)

**Comment by SumoSourabh** [comment]
Can you please tell us which version of Plugin you are using?

**Comment by SumoSourabh** [comment]
Closing it as no input.
