### ISSUE TITLE
no easy way to tell the different kinds of messages apart

### ISSUE THREAD

**Issue by davidcarltonsumo** [SumoLogic/sumologic-jenkins-plugin#7]
I'm trying to generate a report on the failure rate for jobs, so to that end I care about the messages from modules but not, say, the queue information.  (Though I might want a separate report that only cares about the queue information!) And, as far as I can tell, there's no good way to pick out only the messages that I want - I can try searching on `start_time`, since that attribute is present in `BuildModel` but not in the other models and since it's unlikely to show up as a data value for an attribute in another model, but it would be nice if I had a json field `message_type` or something that I could search on to pick the exact messages I want.

**Comment by lchodar** [comment]
Fixed with recent refactoring. Can specify _sourceCategory for different message types in jenkins configuration.
