### ISSUE TITLE
 feature: SumoBuildNotifier global configuration

### ISSUE THREAD

**Issue by forestjohnsonpeoplenet** [SumoLogic/sumologic-jenkins-plugin#8]
I have installed this plugin on Jenkins 2.7.1 and it is posting build executor stats to SumoLogic (SumoPeriodicPublisher) but not doing anything on build success or failure. 

Do I have to do something to enable it? I can't see anything in the settings for that.

**Comment by forestjohnsonpeoplenet** [comment]
Oops my bad, I missed this option in the build steps configuration: 

![screenshot](http://i.imgur.com/hE5bHXy.png)

I still wish there was an option to enable this on all jobs or on all jobs based on some rule.

**Comment by SumoSourabh** [comment]
V 2.0 released
